### ISSUE TITLE
Request for New Feature: Option to Output Logs to Both stderr/stdout and XML File

### ISSUE THREAD

**Issue by ono-max** [kenichiice/test-unit-runner-junitxml#25]
Thank you for developing this fantastic gem! I am a contributor to ruby/debug and I am considering using this gem within ruby/debug. I would like to inquire about the possibility of adding an option to simultaneously output logs to both stderr/stdout and an XML file.

The documentation states:

--junitxml-output-file=FILE_NAME
Output XML to the specified file instead of the standard output.

If I understand correctly, there is currently no option available in test-unit-runner-junitxml to output logs to both stderr/stdout and an XML file.

**Comment by ono-max** [comment]
I'll close this issue as we've decided to implement the feature ourselves. Thank you for your understanding.

**Comment by kenichiice** [comment]
Sorry, I was not aware of this issue.
I think it is possible to implement the feature you suggest, but I need to consider the options for this feature.
Also, if it has been implemented and you can provide a patch, I will consider merging it.

**Comment by kenichiice** [comment]
[ruby/debug](https://github.com/ruby/debug) で必要としていた機能は新しいプラグインにより解決している模様。
* https://github.com/ruby/debug/pull/1090
* https://github.com/ono-max/test-unit-launchable

元々の問題は、GitHub Actions上のUIでエラーの内容を確認できないのが不便だったということみたい。
* https://github.com/ruby/debug/pull/1081
